[[redirects]]
from = "/about"
to = "/about.html"
status = 200

[[redirects]]
from = "/gallery"
to = "/gallery.html"
status = 200

[[redirects]]
from = "/blog"
to = "/blog.html"
status = 200

[[redirects]]
from = "/games"
to = "/games.html"
status = 200

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[build]
command = "npm run build"
publish = "dist"